FROM gradle:7.4-jdk17-alpine AS build

WORKDIR /app
COPY . .
RUN ./gradlew build --no-daemon

FROM openjdk:17-jdk-slim

WORKDIR /app
COPY --from=build /app/build/libs/*.jar ./app.jar

EXPOSE 9000

CMD ["java", "-jar", "app.jar"]